2025-01-21 07:14:27,729 - INFO - Chargement des bibliothèques réussie
2025-01-21 07:14:27,729 - INFO - Début de la pipeline ML : génération de données synthétiques.
2025-01-21 07:14:27,732 - INFO - Division des données en ensembles d'entraînement et de test.
2025-01-21 07:14:27,732 - INFO - Entraînement du modèle RandomForest.
2025-01-21 07:14:27,916 - INFO - Prédictions et évaluation des performances.
2025-01-21 07:14:27,919 - INFO - Précision du modèle : 0.90
2025-01-21 07:14:27,919 - WARNING - Précision inférieure au seuil attendu de 0.95.
                                    Vérifiez les hyperparamètres.
2025-01-21 07:14:27,919 - INFO - Fin de la pipeline ML.
2025-01-21 07:18:55,861 - INFO - Chargement des bibliothèques réussie
2025-01-21 07:18:55,861 - INFO - Début de la pipeline ML : génération de données synthétiques.
2025-01-21 07:18:55,865 - INFO - Division des données en ensembles d'entraînement et de test.
2025-01-21 07:18:55,865 - INFO - Entraînement du modèle RandomForest.
2025-01-21 07:18:56,032 - INFO - Prédictions et évaluation des performances.
2025-01-21 07:18:56,035 - INFO - Précision du modèle : 0.90
2025-01-21 07:18:56,035 - WARNING - Précision inférieure au seuil attendu de 0.95. 
 Vérifiez les hyperparamètres.
2025-01-21 07:18:56,035 - INFO - Fin de la pipeline ML.


2025-01-21 07:20:03,230 - INFO - Chargement des bibliothèques réussie
2025-01-21 07:20:03,230 - INFO - Début de la pipeline ML : génération de données synthétiques.
2025-01-21 07:20:03,233 - INFO - Division des données en ensembles d'entraînement et de test.
2025-01-21 07:20:03,233 - INFO - Entraînement du modèle RandomForest.
2025-01-21 07:20:03,233 - ERROR - Une erreur s'est produite :
RandomForestClassifier.__init__() got an unexpected keyword argument 'random_stat'
Traceback (most recent call last):
  File "/Users/abraham/Desktop/Perso/e-commerce-pipeline/logging-test.py", line 27, in <module>
    model = RandomForestClassifier(random_stat=42)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: RandomForestClassifier.__init__() got an unexpected keyword argument 'random_stat'
2025-01-21 07:20:03,233 - INFO - Fin de la pipeline ML.
